### ISSUE TITLE
Is comment still accurate?

### ISSUE THREAD

**Issue by stephane-alnet** [signalwire/actions-template#1]
https://github.com/signalwire/actions-template/blob/7ef61785e57ba1c2abff0e171bc2f932c5a6d998/.github/workflows/docker-bp.yml#L38

I believe the workflow contains two jobs named `buildpush` and `swarmdeploy`?

**Comment by lucasmellos** [comment]
Hi @stephane-alnet you're right. This was a workaround made ASAP to fulfill one need. A new version is under develop under dev branch.
