### ISSUE TITLE
Document `load` ?

### ISSUE THREAD

**Issue by stephane-alnet** [signalwire/actions-template#2]
https://github.com/signalwire/actions-template/blob/7ef61785e57ba1c2abff0e171bc2f932c5a6d998/.github/workflows/docker-bp.yml#L75

`load` is not documented in https://docs.github.com/en/actions/publishing-packages/publishing-docker-images , it might be helpful to document what its purpose is (I see we have a step with `push: true` later).

**Comment by stephane-alnet** [comment]
I guess it's documented here https://github.com/marketplace/actions/build-and-push-docker-images

So its purpose is… to build an image available locally?

**Comment by stephane-alnet** [comment]
Also https://github.com/docker/metadata-action has a reference for tags etc

**Comment by stephane-alnet** [comment]
And https://github.com/docker/build-push-action is the reference for the action itself

**Comment by lucasmellos** [comment]
You're right. It should be documented in a better way. The purpose is to load the image that has been built previously for testing and reuse it on pushing step
